### ISSUE TITLE
policy_evaluation step fails with "Error: No such container: bash"

### ISSUE THREAD

**Issue by emosbaugh** [anchore/circleci-orbs#5]
the following job fails with error `Error: No such container: bash`

```
  cve-scan:
    executor: anchore/anchore_engine
    environment:
      IMAGES: >-
        golang:1.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - anchore/start_engine
      - anchore/add_private_regis
      - anchore/analyze_image:
          image_name: $IMAGES
      - anchore/policy_evaluation:
          image_name: $IMAGES
          policy_failure: true
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
```

output from circleci

```
Error: No such container: bash
Failed to activate policy bundle .circleci/.anchore/policy_bundle.json - using default policy.
```
